export { BodyPlan, CREATURE_ARCHETYPE_BY_BODYPLAN } from './BodyPlan';
export type { RadiusProfileCurve } from './RadiusProfileCurve';
export { evalRadiusProfile } from './RadiusProfileCurve';
export type { AttachEmitter } from './AttachEmitters';
export { resolveTentacleGroups } from './AttachEmitters';
export type { SpineCurve } from './SpineCurve';
export { evalSpineOffset } from './SpineCurve';
export type { CreatureSpecBase, CreatureSpec, JellyfishSpec, FishSpec, AnemoneSpec, FishFinConfig, JellyfishGeometryConfig } from './CreatureSpec';
export { DEFAULT_GEOMETRY_CONFIG, resolveGeometryConfig } from './CreatureSpec';
export type { PresetId, CreaturePreset } from './presets';
export { PRESETS } from './presets';
export { validateCreatureSpec } from './validate';
export { mutateCreatureSpec } from './mutate';
export type { CreatureRig, CreatureUnit } from './CreatureFactory';
export { createCreatureRig } from './CreatureFactory';
